# Generated by Django 4.0.5 on 2022-06-15 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PageView',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('viewed_on', models.DateTimeField(auto_now_add=True)),
                ('ip_from_proxy', models.GenericIPAddressField(null=True)),
                ('http_x_forwarded_for', models.CharField(max_length=512, null=True)),
                ('path', models.CharField(max_length=512)),
            ],
        ),
    ]
