# Generated by Django 4.0.5 on 2022-06-15 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teablog', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pageview',
            name='http_x_forwarded_for',
        ),
        migrations.RemoveField(
            model_name='pageview',
            name='ip_from_proxy',
        ),
        migrations.AddField(
            model_name='pageview',
            name='ip',
            field=models.GenericIPAddressField(null=True),
        ),
        migrations.AddField(
            model_name='pageview',
            name='user_agent',
            field=models.CharField(default='0.0.0.0', max_length=512),
            preserve_default=False,
        ),
    ]
