# Generated by Django 4.0.5 on 2022-06-15 01:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teablog', '0002_remove_pageview_http_x_forwarded_for_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pageview',
            name='user_agent',
            field=models.CharField(max_length=512, null=True),
        ),
    ]
